// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg2CPA_VgLq2hZEoBMYuljs9rOsSMwmgQ',
    appId: '1:552898568001:web:f351d713ea81a9cf998bc0',
    messagingSenderId: '552898568001',
    projectId: 'redex-chat-app-5dbe8',
    authDomain: 'redex-chat-app-5dbe8.firebaseapp.com',
    storageBucket: 'redex-chat-app-5dbe8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiXxqfVHidhyNeFxmzpt1jC6KrDu8CQec',
    appId: '1:552898568001:android:3778efc7efd8b0de998bc0',
    messagingSenderId: '552898568001',
    projectId: 'redex-chat-app-5dbe8',
    storageBucket: 'redex-chat-app-5dbe8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3sX9U-U5f6myMgVWCvQas5g353T3_1lY',
    appId: '1:552898568001:ios:5437abdbaab3306e998bc0',
    messagingSenderId: '552898568001',
    projectId: 'redex-chat-app-5dbe8',
    storageBucket: 'redex-chat-app-5dbe8.appspot.com',
    iosBundleId: 'com.example.redexChatApp',
  );
}
