// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwNfTrnjYk-UG6WaeFzlTr13gdi31CFOs',
    appId: '1:1054537037589:android:4b52f86f9207594e5ddb1c',
    messagingSenderId: '1054537037589',
    projectId: 'redex-final',
    databaseURL: 'https://redex-final-default-rtdb.firebaseio.com',
    storageBucket: 'redex-final.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAicDo-KvxIounW7Bf3Nh2OcEGk29nhog',
    appId: '1:1054537037589:ios:a3d2f8beee5db47a5ddb1c',
    messagingSenderId: '1054537037589',
    projectId: 'redex-final',
    databaseURL: 'https://redex-final-default-rtdb.firebaseio.com',
    storageBucket: 'redex-final.appspot.com',
    iosBundleId: 'com.example.chtingApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxcLOm2jFIVLqw257_U4h0eUWWOIMsJNY',
    appId: '1:1054537037589:web:85bb448919ebcec05ddb1c',
    messagingSenderId: '1054537037589',
    projectId: 'redex-final',
    authDomain: 'redex-final.firebaseapp.com',
    databaseURL: 'https://redex-final-default-rtdb.firebaseio.com',
    storageBucket: 'redex-final.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAicDo-KvxIounW7Bf3Nh2OcEGk29nhog',
    appId: '1:1054537037589:ios:a3d2f8beee5db47a5ddb1c',
    messagingSenderId: '1054537037589',
    projectId: 'redex-final',
    databaseURL: 'https://redex-final-default-rtdb.firebaseio.com',
    storageBucket: 'redex-final.appspot.com',
    iosBundleId: 'com.example.chtingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxcLOm2jFIVLqw257_U4h0eUWWOIMsJNY',
    appId: '1:1054537037589:web:bb50a81fc78f880f5ddb1c',
    messagingSenderId: '1054537037589',
    projectId: 'redex-final',
    authDomain: 'redex-final.firebaseapp.com',
    databaseURL: 'https://redex-final-default-rtdb.firebaseio.com',
    storageBucket: 'redex-final.appspot.com',
  );

}