// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAydTKsmC1KBJKnQ1mTt8HyK0itsRmeesc',
    appId: '1:810967697425:web:85fa4c23b38424d0ee49b0',
    messagingSenderId: '810967697425',
    projectId: 'redex-29b56',
    authDomain: 'redex-29b56.firebaseapp.com',
    databaseURL: 'https://redex-29b56-default-rtdb.firebaseio.com',
    storageBucket: 'redex-29b56.appspot.com',
    measurementId: 'G-5BVH08D443',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSUQds4Ddouymf2HGiZ7v_j3oBMdN0Hk4',
    appId: '1:810967697425:android:afe5081b483c6e23ee49b0',
    messagingSenderId: '810967697425',
    projectId: 'redex-29b56',
    databaseURL: 'https://redex-29b56-default-rtdb.firebaseio.com',
    storageBucket: 'redex-29b56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5FoozioXqGS8PwgtLfWEC9oicz7nYXhY',
    appId: '1:810967697425:ios:407aee052344d028ee49b0',
    messagingSenderId: '810967697425',
    projectId: 'redex-29b56',
    databaseURL: 'https://redex-29b56-default-rtdb.firebaseio.com',
    storageBucket: 'redex-29b56.appspot.com',
    iosBundleId: 'com.example.redex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5FoozioXqGS8PwgtLfWEC9oicz7nYXhY',
    appId: '1:810967697425:ios:407aee052344d028ee49b0',
    messagingSenderId: '810967697425',
    projectId: 'redex-29b56',
    databaseURL: 'https://redex-29b56-default-rtdb.firebaseio.com',
    storageBucket: 'redex-29b56.appspot.com',
    iosBundleId: 'com.example.redex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAydTKsmC1KBJKnQ1mTt8HyK0itsRmeesc',
    appId: '1:810967697425:web:9bdf724012054a84ee49b0',
    messagingSenderId: '810967697425',
    projectId: 'redex-29b56',
    authDomain: 'redex-29b56.firebaseapp.com',
    databaseURL: 'https://redex-29b56-default-rtdb.firebaseio.com',
    storageBucket: 'redex-29b56.appspot.com',
    measurementId: 'G-024C5R3WT7',
  );
}
